gen-code:
protoc --go-grpc_out=. calculator.proto
protoc --go_out=. calculator.proto
D:\GOPATH\src\grpc_course\calculator\calculatorpb>
server:
go run server/server.go

client:
go run client/client.go